import { Product, Category, BlogPost, Announcement, SiteSettings, Order, Customer, InventoryHistoryItem } from '@/types/database';

export const initialSiteSettings: SiteSettings = {
  id: '00000000-0000-0000-0000-000000000001',
  brand_name: 'InkThread Hub',
  tagline: 'Heavyweight Artisanal Streetwear & Underground Drops',
  logo_url: '/favicon.svg',
  contact_email: 'support@inkthreadhub.com',
  support_phone: '+91 98765 43210',
  currency: 'INR',
  currency_symbol: '₹',
  free_shipping_threshold: 999,
  default_shipping_fee: 99,
  tax_percent: 5,
  instagram_url: 'https://instagram.com/inkthreadhub',
  twitter_url: 'https://twitter.com/inkthreadhub',
  facebook_url: 'https://facebook.com/inkthreadhub',
  store_address: 'Plot 42, Okhla Industrial Area Phase III',
  city: 'New Delhi',
  state: 'Delhi',
  pincode: '110020',
  announcement_bar_enabled: true,
  announcement_bar_text: '⚡ FLASH DROP: 20% OFF ON ORDERS OVER ₹1,499 | USE CODE: STREET20',
};

export const initialCategories: Category[] = [
  {
    id: '11111111-1111-1111-1111-111111110001',
    name: 'Oversized T-Shirts',
    slug: 'oversized-t-shirts',
    description: '240 GSM heavyweight boxy fit drops with drop-shoulder silhouettes.',
    image_url: '/images/plain_oversized_black.jpg',
    is_active: true,
    display_order: 1,
  },
  {
    id: '11111111-1111-1111-1111-111111110002',
    name: 'Heavyweight Hoodies',
    slug: 'heavyweight-hoodies',
    description: '380 GSM fleece and French terry hoodies engineered for comfort & drape.',
    image_url: '/images/hd_acidwash_hoodie.png',
    is_active: true,
    display_order: 2,
  },
  {
    id: '11111111-1111-1111-1111-111111110003',
    name: 'Graphic Drops',
    slug: 'graphic-drops',
    description: 'Artisanal anime, mythology, and dark-aesthetic screen-printed streetwear.',
    image_url: '/images/sungod_luffy_acidwash_front.jpg',
    is_active: true,
    display_order: 3,
  },
  {
    id: '11111111-1111-1111-1111-111111110004',
    name: 'Jackets & Outerwear',
    slug: 'jackets-outerwear',
    description: 'All-over print bombers and heavyweight varsity streetwear outerwear.',
    image_url: '/images/hd_aop_bomber.png',
    is_active: true,
    display_order: 4,
  },
  {
    id: '11111111-1111-1111-1111-111111110005',
    name: 'Streetwear Accessories',
    slug: 'streetwear-accessories',
    description: 'Totes, caps, brass-buckle pet collars and utility lifestyle pieces.',
    image_url: '/images/hd_tote_bag.png',
    is_active: true,
    display_order: 5,
  },
];

export const initialProducts: Product[] = [
  {
    id: '22222222-2222-2222-2222-222222220001',
    name: 'SunGod Luffy Acid Wash Graphic Hoodie',
    slug: 'sungod-luffy-acid-wash-hoodie',
    sku: 'ITH-HD-SGL-01',
    description: 'The crowning piece of our Gear 5 drop. Features an ultra-heavy 380 GSM loop-knit French Terry with artisanal acid-wash distressing, custom embroidered chest detail, and a massive high-density back print depicting Sun God Luffy in mythological resonance. Ribbed hems, oversized kangaroo pocket, and double-layered heavyweight hood.',
    short_description: '380 GSM Heavyweight French Terry with artisanal acid-wash and mythology high-density screenprint.',
    category_id: '11111111-1111-1111-1111-111111110002',
    category_name: 'Heavyweight Hoodies',
    product_type: 'Heavyweight Hoodie',
    price: 2499,
    sale_price: 1999,
    cost_price: 850,
    discount_percent: 20,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Acid Wash Grey', 'Obsidian Black', 'Chalk White'],
    thumbnail: '/images/hd_acidwash_hoodie.png',
    images: [
      '/images/hd_acidwash_hoodie.png',
      '/images/sungod_luffy_acidwash_front.jpg',
      '/images/sungod_luffy_acidwash_back.jpg',
      '/images/sungod_luffy_black_hoodie.jpg',
    ],
    is_published: true,
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    stock_quantity: 45,
    low_stock_threshold: 5,
    fabric_gsm: 380,
    material_care: '100% Cotton French Terry. 380 GSM. Pre-shrunk & Acid Washed. Wash cold inside out.',
    seo_title: 'SunGod Luffy Acid Wash Streetwear Hoodie | InkThread Hub',
    seo_description: 'Shop the ultra-heavy 380 GSM SunGod Luffy Acid Wash Hoodie with high-density screenprint.',
  },
  {
    id: '22222222-2222-2222-2222-222222220002',
    name: 'Vintage SunGod Graphic Oversized Tee',
    slug: 'vintage-sungod-graphic-oversized-tee',
    sku: 'ITH-TEE-SGC-02',
    description: 'Crafted with 240 GSM pure combed cotton. Features a relaxed drop-shoulder cut, thick 1.25-inch ribbed crewneck collar, and durable discharge screen-printing that never cracks or peels.',
    short_description: '240 GSM boxy oversized drop with mythological Sun God discharge print.',
    category_id: '11111111-1111-1111-1111-111111110001',
    category_name: 'Oversized T-Shirts',
    product_type: 'Oversized T-Shirt',
    price: 1299,
    sale_price: 899,
    cost_price: 380,
    discount_percent: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Obsidian Black', 'Vintage Off-White'],
    thumbnail: '/images/sungod_classic_black_front.jpg',
    images: [
      '/images/sungod_classic_black_front.jpg',
      '/images/sungod_classic_black_back.jpg',
      '/images/sungod_classic_white_front.jpg',
      '/images/sungod_classic_white_back.jpg',
    ],
    is_published: true,
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: true,
    stock_quantity: 80,
    low_stock_threshold: 10,
    fabric_gsm: 240,
    material_care: '100% Super-Combed Cotton. 240 GSM Heavyweight Jersey. Machine wash cold.',
    seo_title: 'Vintage SunGod Graphic Oversized Tee | InkThread Hub',
    seo_description: 'Heavyweight 240 GSM oversized streetwear t-shirt with durable vintage discharge print.',
  },
  {
    id: '22222222-2222-2222-2222-222222220003',
    name: 'All-Over Print Street Bomber Jacket',
    slug: 'all-over-print-street-bomber-jacket',
    sku: 'ITH-JKT-BMB-03',
    description: 'Engineered for maximum street presence. Premium satin polyester shell with all-over custom artwork sublimated under heat pressure. Diamond-quilted inner insulation lining, heavy brass zipper, and ribbed athletic cuffs.',
    short_description: 'Insulated all-over sublimated streetwear bomber with heavy brass hardware.',
    category_id: '11111111-1111-1111-1111-111111110004',
    category_name: 'Jackets & Outerwear',
    product_type: 'Bomber Jacket',
    price: 3499,
    sale_price: 2799,
    cost_price: 1200,
    discount_percent: 20,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Cyber Obsidian', 'Neon Abstract'],
    thumbnail: '/images/hd_aop_bomber.png',
    images: ['/images/hd_aop_bomber.png', '/images/hd_varsity_jacket.png'],
    is_published: true,
    is_featured: true,
    is_new_arrival: true,
    is_best_seller: false,
    stock_quantity: 28,
    low_stock_threshold: 4,
    fabric_gsm: 320,
    material_care: 'Water-resistant poly-satin shell with polyester diamond-quilted fill. Wipe clean or dry clean only.',
    seo_title: 'All-Over Print Street Bomber Jacket | InkThread Hub',
    seo_description: 'Elevate your streetwear layering with the insulated AOP Bomber Jacket by InkThread Hub.',
  },
  {
    id: '22222222-2222-2222-2222-222222220004',
    name: 'Mandala Elephant Oversized Boxy Tee',
    slug: 'mandala-elephant-oversized-tee',
    sku: 'ITH-TEE-MDE-04',
    description: 'A synthesis of Indian artisanal sacred geometry and raw modern streetwear. Intricate mandala elephant back-canvas printed with metallic-fleck and soft matte pigment ink on 240 GSM heavyweight cotton.',
    short_description: 'Sacred geometry mandala elephant print on 240 GSM boxy streetwear tee.',
    category_id: '11111111-1111-1111-1111-111111110003',
    category_name: 'Graphic Drops',
    product_type: 'Oversized T-Shirt',
    price: 1199,
    sale_price: 799,
    cost_price: 350,
    discount_percent: 33,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Obsidian Black', 'Forest Sage', 'Chalk White'],
    thumbnail: '/images/mandala_elephant_front.jpg',
    images: ['/images/mandala_elephant_front.jpg', '/images/mandala_elephant_back.jpg'],
    is_published: true,
    is_featured: false,
    is_new_arrival: true,
    is_best_seller: true,
    stock_quantity: 60,
    low_stock_threshold: 8,
    fabric_gsm: 240,
    material_care: '100% Combed Cotton. 240 GSM. Gentle machine wash inside out in cold water.',
    seo_title: 'Mandala Elephant Oversized Boxy Tee | InkThread Hub',
    seo_description: 'Shop the Mandala Elephant Oversized Streetwear Tee with metallic and matte pigment ink.',
  },
  {
    id: '22222222-2222-2222-2222-222222220005',
    name: 'Essential Minimalist Heavyweight Plain Tee',
    slug: 'essential-minimalist-heavyweight-plain-tee',
    sku: 'ITH-TEE-PLN-05',
    description: 'The holy grail of streetwear basics. Zero loud branding, pristine tailoring. Cut with extra wide shoulders, elbow-length sleeves, and high-density bio-washed 240 GSM jersey that holds its structural shape wash after wash.',
    short_description: '240 GSM essential plain heavyweight tee with structural boxy fit.',
    category_id: '11111111-1111-1111-1111-111111110001',
    category_name: 'Oversized T-Shirts',
    product_type: 'Oversized T-Shirt',
    price: 999,
    sale_price: 699,
    cost_price: 290,
    discount_percent: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Obsidian Black', 'Chalk White', 'Forest Green', 'Navy Blue', 'Teal Mist'],
    thumbnail: '/images/plain_oversized_black.jpg',
    images: [
      '/images/plain_oversized_black.jpg',
      '/images/plain_oversized_white.jpg',
      '/images/plain_oversized_green.jpg',
      '/images/plain_oversized_navy.jpg',
      '/images/plain_oversized_teal.jpg',
    ],
    is_published: true,
    is_featured: true,
    is_new_arrival: false,
    is_best_seller: true,
    stock_quantity: 120,
    low_stock_threshold: 15,
    fabric_gsm: 240,
    material_care: '100% Ring-Spun Cotton. 240 GSM. Bio-washed for ultra-soft handfeel. Cold wash.',
    seo_title: 'Essential Heavyweight Plain Oversized Tee | InkThread Hub',
    seo_description: 'The cleanest streetwear basic. 240 GSM heavyweight boxy oversized plain t-shirt.',
  },
  {
    id: '22222222-2222-2222-2222-222222220006',
    name: 'Heavy-Duty Canvas Street Tote Bag',
    slug: 'heavy-duty-canvas-street-tote-bag',
    sku: 'ITH-ACC-TOT-06',
    description: 'Built from ultra-durable 16oz cotton duck canvas with reinforced cross-stitched webbing handles, interior zip organizer pocket for keys and phone, and screenprinted typographic street manifesto.',
    short_description: '16oz Heavyweight Canvas Tote with interior zippered stash pocket.',
    category_id: '11111111-1111-1111-1111-111111110005',
    category_name: 'Streetwear Accessories',
    product_type: 'Accessories',
    price: 799,
    sale_price: 499,
    cost_price: 180,
    discount_percent: 37,
    sizes: ['One Size'],
    colors: ['Natural Canvas', 'Obsidian Black'],
    thumbnail: '/images/hd_tote_bag.png',
    images: ['/images/hd_tote_bag.png'],
    is_published: true,
    is_featured: false,
    is_new_arrival: true,
    is_best_seller: false,
    stock_quantity: 50,
    low_stock_threshold: 5,
    fabric_gsm: 450,
    material_care: '100% 16oz Cotton Duck Canvas. Spot clean with damp cloth.',
    seo_title: 'Heavy-Duty Street Canvas Tote Bag | InkThread Hub',
    seo_description: 'Heavyweight 16oz canvas tote bag with reinforced handles and interior zip stash pocket.',
  },
  {
    id: '22222222-2222-2222-2222-222222220007',
    name: 'Artisanal Brass Buckle Pet Belt & Collar | PC01',
    slug: 'pet-neck-belt-bracket-collar-pc01',
    sku: 'ITH-PET-COL-07',
    description: 'Crafted for our urban companion collection. Genuine full-grain leather with anti-rust solid brass buckle, reinforced alloy brackets, and secure D-ring for leash attachment.',
    short_description: 'Heavy-duty genuine full-grain leather pet neck belt with solid brass hardware.',
    category_id: '11111111-1111-1111-1111-111111110005',
    category_name: 'Streetwear Accessories',
    product_type: 'Pet Accessories',
    price: 799,
    sale_price: 499,
    cost_price: 200,
    discount_percent: 37,
    sizes: ['S (Small Dogs/Cats)', 'M (Medium Dogs)', 'L (Large Dogs)'],
    colors: ['Tan Brown', 'Obsidian Black', 'Ruby Red'],
    thumbnail: '/images/hd_pet_collar.png',
    images: ['/images/hd_pet_collar.png'],
    is_published: true,
    is_featured: false,
    is_new_arrival: true,
    is_best_seller: false,
    stock_quantity: 35,
    low_stock_threshold: 5,
    fabric_gsm: 0,
    material_care: 'Full-grain leather and solid brass. Condition with leather balm.',
    seo_title: 'Brass Buckle Pet Neck Belt Collar | InkThread Hub',
    seo_description: 'Heavy-duty genuine leather pet belt collar with solid brass hardware by InkThread Hub.',
  },
];

export const initialBlogPosts: BlogPost[] = [
  {
    id: '33333333-3333-3333-3333-333333330001',
    title: 'The Anatomy of 240 GSM: Why Heavyweight Cotton Defines Modern Streetwear',
    slug: 'the-anatomy-of-240-gsm-heavyweight-streetwear',
    excerpt: 'Discover why flimsy 140 GSM tees are obsolete and how 240+ GSM French Terry and heavy jersey create the iconic boxy drape coveted across streetwear culture.',
    content: `## The Death of Flimsy Fabrics\n\nFor decades, fast fashion normalized paper-thin 140-160 GSM cotton that lost its structural integrity after two laundry cycles. But the rise of modern Gen-Z streetwear culture flipped the script.\n\n### What Exactly is GSM?\n\nGSM stands for *Grams per Square Meter*. It is the objective metric of textile density.\n- **140 - 160 GSM**: Lightweight, transparent under sunlight, collapses onto the body without structure.\n- **180 - 200 GSM**: Standard commercial t-shirt weight.\n- **240 - 280 GSM (The InkThread Standard)**: Heavyweight, opaque, rigid drape, perfect boxy silhouette.\n- **350 - 400 GSM**: Premium fleece and French Terry used in luxury hoodies.\n\n### Why Structure Matters in Streetwear\n\nA true drop-shoulder oversized tee requires a fabric with enough tensile memory to hold a crisp line from the shoulder seam down to the elbow. When you slip on an InkThread Hub 240 GSM tee, it doesn't cling—it creates a structured, architectural silhouette.`,
    featured_image: '/images/plain_oversized_black.jpg',
    category: 'Streetwear Culture',
    tags: ['Streetwear', 'Fabric Guide', 'GSM', 'Oversized Fit'],
    author: 'Arjun Varma (Creative Lead)',
    is_published: true,
    published_at: '2026-08-16',
    read_time: '4 min read',
    seo_title: 'Why 240 GSM Heavyweight Cotton Defines Streetwear | InkThread Hub',
    seo_description: 'An in-depth look at GSM textile density and why heavyweight 240 GSM cotton is essential for streetwear silhouettes.',
  },
  {
    id: '33333333-3333-3333-3333-333333330002',
    title: 'Behind the Drop: Reimagining SunGod Mythology Through Acid-Wash Artistry',
    slug: 'behind-the-drop-sungod-acid-wash-artistry',
    excerpt: 'A look behind the scenes of our signature SunGod drop—from hand-drawn high-density vector illustrations to manual stone-wash distressing.',
    content: `## Myth Meets the Concrete Jungle\n\nStreetwear is about storytelling through wearable art. For our SunGod series, our design team spent three months conceptualizing ancient solar deities and manga-inspired warrior awakenings into high-contrast screenprints.\n\n### The Acid Wash Process\n\nNo two pieces from the SunGod collection are identical. Each garment undergoes a hand-applied potassium permanganate spray followed by pumice stone tumbling. This breaks down the surface dye while leaving the 380 GSM cotton fibers resilient and buttery soft.`,
    featured_image: '/images/sungod_luffy_acidwash_front.jpg',
    category: 'Lookbook & Design',
    tags: ['Design', 'Drop', 'Anime', 'Acid Wash'],
    author: 'InkThread Atelier',
    is_published: true,
    published_at: '2026-08-14',
    read_time: '5 min read',
    seo_title: 'Behind the SunGod Streetwear Drop | InkThread Hub',
    seo_description: 'Explore the creation of our signature SunGod acid-wash drop and artisanal screenprinting techniques.',
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: '55555555-5555-5555-5555-555555550001',
    title: 'Gear 5 Acid Wash Drop',
    message: '⚡ NEW DROP: SunGod Acid Wash 380 GSM Hoodies are live in limited quantities.',
    type: 'drop',
    link_url: '/shop?category=heavyweight-hoodies',
    is_active: true,
    priority: 1,
  },
  {
    id: '55555555-5555-5555-5555-555555550002',
    title: 'Free Shipping Pan-India',
    message: '🚚 Free express shipping on all prepaid orders above ₹999.',
    type: 'general',
    link_url: '/shop',
    is_active: true,
    priority: 2,
  },
];

export const initialOrders: Order[] = [
  {
    id: '66666666-6666-6666-6666-666666660001',
    order_number: 'ITH-2026-08101',
    customer_name: 'Rohan Deshmukh',
    customer_email: 'rohan.deshmukh@example.com',
    customer_phone: '+91 98200 12345',
    shipping_address: {
      address_line1: 'Flat 402, Sea Breeze Heights, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
    },
    subtotal: 1999,
    discount_amount: 200,
    coupon_code: 'STREET10',
    shipping_fee: 0,
    tax_amount: 90,
    total_amount: 1889,
    status: 'Shipped',
    payment_status: 'Paid',
    payment_method: 'Razorpay (UPI - Google Pay)',
    razorpay_order_id: 'order_Nx8Y29s8dl12aA',
    razorpay_payment_id: 'pay_Nx8Z39k9sm23bB',
    tracking_courier: 'Blue Dart Express',
    tracking_number: 'BLUEDART-883920194',
    internal_notes: 'VIP customer, pack with complimentary stickers pack.',
    timeline: [
      { status: 'Pending Payment', timestamp: '2026-08-18T10:14:00Z', description: 'Order placed by customer' },
      { status: 'Paid', timestamp: '2026-08-18T10:15:30Z', description: 'Payment verified via Razorpay UPI (pay_Nx8Z39k9sm23bB)' },
      { status: 'Processing', timestamp: '2026-08-18T12:00:00Z', description: 'Order verified & allocated at Delhi Atelier' },
      { status: 'Packed', timestamp: '2026-08-19T09:30:00Z', description: 'Packed in matte black rigid box' },
      { status: 'Shipped', timestamp: '2026-08-19T14:20:00Z', description: 'Dispatched via Blue Dart (AWB: BLUEDART-883920194)' },
    ],
    items: [
      {
        product_id: '22222222-2222-2222-2222-222222220001',
        product_name: 'SunGod Luffy Acid Wash Graphic Hoodie',
        product_slug: 'sungod-luffy-acid-wash-hoodie',
        product_sku: 'ITH-HD-SGL-01',
        product_image: '/images/hd_acidwash_hoodie.png',
        size: 'L',
        color: 'Acid Wash Grey',
        quantity: 1,
        unit_price: 1999,
        total_price: 1999,
      },
    ],
    created_at: '2026-08-18T10:14:00Z',
    updated_at: '2026-08-19T14:20:00Z',
  },
  {
    id: '66666666-6666-6666-6666-666666660002',
    order_number: 'ITH-2026-08102',
    customer_name: 'Ananya Roy',
    customer_email: 'ananya.roy@example.com',
    customer_phone: '+91 98300 54321',
    shipping_address: {
      address_line1: 'B-12, Salt Lake Sector V',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700091',
    },
    subtotal: 1598,
    discount_amount: 0,
    shipping_fee: 0,
    tax_amount: 80,
    total_amount: 1678,
    status: 'Delivered',
    payment_status: 'Paid',
    payment_method: 'Razorpay (Credit Card)',
    razorpay_order_id: 'order_Ox9A30t9em34cC',
    razorpay_payment_id: 'pay_Ox9B40l0tn45dD',
    tracking_courier: 'Delhivery Surface',
    tracking_number: 'DLHV-994827164',
    timeline: [
      { status: 'Pending Payment', timestamp: '2026-08-15T14:30:00Z', description: 'Order created' },
      { status: 'Paid', timestamp: '2026-08-15T14:32:10Z', description: 'Payment verified via Razorpay' },
      { status: 'Processing', timestamp: '2026-08-15T16:00:00Z', description: 'Order processed' },
      { status: 'Packed', timestamp: '2026-08-16T11:00:00Z', description: 'Packed & labeled' },
      { status: 'Shipped', timestamp: '2026-08-16T17:00:00Z', description: 'In transit to Kolkata' },
      { status: 'Delivered', timestamp: '2026-08-18T16:45:00Z', description: 'Delivered to recipient' },
    ],
    items: [
      {
        product_id: '22222222-2222-2222-2222-222222220002',
        product_name: 'Vintage SunGod Graphic Oversized Tee',
        product_slug: 'vintage-sungod-graphic-oversized-tee',
        product_sku: 'ITH-TEE-SGC-02',
        product_image: '/images/sungod_classic_black_front.jpg',
        size: 'M',
        color: 'Obsidian Black',
        quantity: 1,
        unit_price: 899,
        total_price: 899,
      },
      {
        product_id: '22222222-2222-2222-2222-222222220005',
        product_name: 'Essential Minimalist Heavyweight Plain Tee',
        product_slug: 'essential-minimalist-heavyweight-plain-tee',
        product_sku: 'ITH-TEE-PLN-05',
        product_image: '/images/plain_oversized_black.jpg',
        size: 'M',
        color: 'Chalk White',
        quantity: 1,
        unit_price: 699,
        total_price: 699,
      },
    ],
    created_at: '2026-08-15T14:30:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
];

export const initialInventoryHistory: InventoryHistoryItem[] = [
  {
    id: '77777777-7777-7777-7777-777777770001',
    product_name: 'SunGod Luffy Acid Wash Graphic Hoodie',
    sku: 'ITH-HD-SGL-01',
    previous_quantity: 46,
    new_quantity: 45,
    quantity_changed: -1,
    reason: 'Order Placement & Payment Confirmation',
    order_id: '66666666-6666-6666-6666-666666660001',
    admin_user: 'Razorpay Webhook',
    created_at: '2026-08-18T10:15:30Z',
  },
  {
    id: '77777777-7777-7777-7777-777777770002',
    product_name: 'Vintage SunGod Graphic Oversized Tee',
    sku: 'ITH-TEE-SGC-02',
    previous_quantity: 50,
    new_quantity: 80,
    quantity_changed: 30,
    reason: 'Supplier Batch Restock (Ludhiana Knit Unit)',
    admin_user: 'Super Admin',
    created_at: '2026-08-17T09:00:00Z',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: '88888888-8888-8888-8888-888888880001',
    full_name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@example.com',
    phone: '+91 98200 12345',
    total_orders: 2,
    total_spent: 3888,
    accepts_marketing: true,
    created_at: '2026-08-01T12:00:00Z',
  },
  {
    id: '88888888-8888-8888-8888-888888880002',
    full_name: 'Ananya Roy',
    email: 'ananya.roy@example.com',
    phone: '+91 98300 54321',
    total_orders: 1,
    total_spent: 1678,
    accepts_marketing: true,
    created_at: '2026-08-15T14:00:00Z',
  },
  {
    id: '88888888-8888-8888-8888-888888880003',
    full_name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    phone: '+91 99110 88776',
    total_orders: 3,
    total_spent: 6490,
    accepts_marketing: false,
    created_at: '2026-07-20T10:00:00Z',
  },
];
