[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://inkthreadhub.in/*"
  to = "https://www.inkthreadhub.in/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "20"

# Redeploy trigger: 2026-08-21
